// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChN6SSSPzNSRk71za-EdxcEHytT--8P7o',
    appId: '1:53231880631:web:74f2d0bf7b53432fa8c032',
    messagingSenderId: '53231880631',
    projectId: 'food-tiger-2',
    authDomain: 'food-tiger-2.firebaseapp.com',
    storageBucket: 'food-tiger-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZuSvcyJslwViKQ-3xw8IV9mRyYVNGtKQ',
    appId: '1:53231880631:android:0083a2818397e37aa8c032',
    messagingSenderId: '53231880631',
    projectId: 'food-tiger-2',
    storageBucket: 'food-tiger-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEfxOGmOn0VdWREH_L2ATX5YinPIK3UaQ',
    appId: '1:53231880631:ios:c9584e8f6b044817a8c032',
    messagingSenderId: '53231880631',
    projectId: 'food-tiger-2',
    storageBucket: 'food-tiger-2.firebasestorage.app',
    iosClientId: '53231880631-hi0c7t73jgudvt6o051519dd91eeb49q.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodTiger',
  );

}